---
title: "GSEA - Ech RNAseq"
output: html_document
date: "2026-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Analyse GSEA sur les données des génisses RNAseq

```{r}
library(openxlsx)
library(limpa)
library(dplyr)
library(stringr)
library(ade4)
library(adegraphics)
library(mixOmics)


y.peptide <- readDIANN("~/work/DIANN_1_9_PRATEG_serie2/report.tsv")

metadata_all = read.xlsx("~/work/Cohorte 2_Synthèse TE PRATEG - Corrigé.xlsx",sheet=2)[1:206,]

table(metadata_all$Catégories)

metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR5502758014"] = "FR5502750001"
metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR4321815388"] = "FR4321810002"
metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR5502730548"] = "FR5502730003"

metadata_all$code_num = substr(metadata_all$ID.receveuse, nchar(metadata_all$ID.receveuse) - 3, nchar(metadata_all$ID.receveuse))

colnames(y.peptide$E)[colnames(y.peptide$E)=="5-31-2025_93_8014_G_12536"]="5-31-2025_93_0001_G_12536"
colnames(y.peptide$E)[colnames(y.peptide$E)=="4-26-2025_134_5388_NG_12062"]="4-26-2025_134_0002_NG_12062"
colnames(y.peptide$E)[colnames(y.peptide$E)=="6-2-2025_175_0548_NG_12600"]="6-2-2025_175_0003_NG_12600"
colnames(y.peptide$E)[colnames(y.peptide$E)=="5-30-2025_113_08437_PE_12511"]="5-30-2025_113_8437_PE_12511"

sample_all = colnames(y.peptide$E)

sample = as.data.frame(colnames(y.peptide$E))
colnames(sample) = "sample_ID"

sample_mat = data.frame()

for (i in sample$sample_ID){
  code_num = (str_split(i, "_")[[1]])[3]
  sample_mat = rbind(sample_mat, c(i,code_num))
  
}

names(sample_mat) = c("sample_ID", "code_num")

metadata = merge(sample_mat,metadata_all,by = "code_num",sort = FALSE)

metadata$Catégories = ifelse(metadata$Catégories == "NR", "NG", "G")

y.peptide$E = y.peptide$E[,metadata$sample_ID]

dim(y.peptide$E)

dim(metadata)

y.peptide <- filterNonProteotypicPeptides(y.peptide)
y.peptide <- filterCompoundProteins(y.peptide)

mean(is.na(y.peptide$E))


dpcfit <- dpc(y.peptide)

dpcfit$dpc

plotDPC(dpcfit)

y.protein <- dpcQuant(y.peptide, protein.id = "Protein.Group", dpc=dpcfit)
```

```{r}
library("clusterProfiler")
library("org.Bt.eg.db")

Group <- factor(metadata$Catégories)
design <- model.matrix(~ 0 + Group)
dim(design)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.protein, design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

hist(fit2$p.value,100)

summary(decideTests(fit2,adjust.method="BH",p.value=0.05))

res = topTable(fit2, coef = 1, number = Inf, adjust.method = "BH")
res_index = order(res$P.Value,decreasing = T)
res = as.data.frame(res[res_index,])

df = res %>% 
  mutate(rank_score = sign(logFC) * -log10(P.Value)) %>% arrange(desc(rank_score))



ids = bitr(rownames(res), fromType = "UNIPROT", toType = "SYMBOL", OrgDb = org.Bt.eg.db)
df = df[ids$UNIPROT,]
df = cbind(df, ids$SYMBOL)

df_unique = df %>% group_by(`ids$SYMBOL`) %>% slice_max(order_by = abs(rank_score), n=1, with_ties = FALSE) %>% ungroup()
df_unique = df_unique[!is.na(df_unique$rank_score),]
df_unique = df_unique[!is.infinite(df_unique$rank_score),]
df_unique = df_unique[df_unique$`ids$SYMBOL` != "" & !is.na(df_unique$`ids$SYMBOL`),]

df_unique = df_unique[order(df_unique$rank_score, decreasing = T),]

gene_list = df_unique$rank_score
names(gene_list) = df_unique$`ids$SYMBOL`

library("msigdbr")
bpth = msigdbr(species = "Bos taurus", category = "C2", subcategory = "CP")
pth_gmt = bpth %>% dplyr::select(gs_name, gene_symbol)

gse_G_vs_NG <- GSEA(geneList =gene_list, 
             TERM2GENE = pth_gmt,
             minGSSize = 3, 
             maxGSSize = 500,
             pvalueCutoff = 1,
             verbose = FALSE,
             pAdjustMethod = "BH")

dotplot(gse_G_vs_NG, showCategory=nrow(gse_G_vs_NG), 
        title = "Enriched MsigDB terms")

```

```{r}
gse_G_vs_NG <- gseGO(geneList = gene_list, 
             ont ="BP", 
             keyType = "SYMBOL", 
             minGSSize = 3, 
             maxGSSize = 100,
             pvalueCutoff = 1,
             verbose = FALSE,
             OrgDb = org.Bt.eg.db, 
             pAdjustMethod = "BH")

dotplot(gse_G_vs_NG, showCategory=5, 
        split=".sign", title = "Enriched GO terms")
```
