---
title: "proteo_cohorte 2"
output: html_document
date: "2026-07-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(openxlsx)
library(limpa)
library(dplyr)
library(stringr)
library(ade4)
library(adegraphics)
library(mixOmics)
library(caret)

y.peptide <- readDIANN("~/work/DIANN_1_9_PRATEG_serie2/report.tsv")

metadata_all = read.xlsx("~/work/Cohorte 2_Synthèse TE PRATEG - Corrigé.xlsx",sheet=2)[1:206,]


metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR5502758014"] = "FR5502750001"
metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR4321815388"] = "FR4321810002"
metadata_all$ID.receveuse[metadata_all$ID.receveuse=="FR5502730548"] = "FR5502730003"

metadata_all$code_num = substr(metadata_all$ID.receveuse, nchar(metadata_all$ID.receveuse) - 3, nchar(metadata_all$ID.receveuse))

colnames(y.peptide$E)[colnames(y.peptide$E)=="5-31-2025_93_8014_G_12536"]="5-31-2025_93_0001_G_12536"
colnames(y.peptide$E)[colnames(y.peptide$E)=="4-26-2025_134_5388_NG_12062"]="4-26-2025_134_0002_NG_12062"
colnames(y.peptide$E)[colnames(y.peptide$E)=="6-2-2025_175_0548_NG_12600"]="6-2-2025_175_0003_NG_12600"
colnames(y.peptide$E)[colnames(y.peptide$E)=="5-30-2025_113_08437_PE_12511"]="5-30-2025_113_8437_PE_12511"

sample_all = colnames(y.peptide$E)

sample = as.data.frame(colnames(y.peptide$E))
colnames(sample) = "sample_ID"

sample_mat = data.frame()

for (i in sample$sample_ID){
  code_num = (str_split(i, "_")[[1]])[3]
  sample_mat = rbind(sample_mat, c(i,code_num))
  
}

names(sample_mat) = c("sample_ID", "code_num")

metadata = merge(sample_mat,metadata_all,by = "code_num",sort = FALSE)
metadata$Date.du.TE = as.Date(metadata$Date.du.TE, origin = "1899-12-30")
metadata$Date.du.TE = format(metadata$Date.du.TE, "%m-%d-%Y")

metadata$code_num = substr(metadata$ID.receveuse, nchar(metadata$ID.receveuse)-3,nchar(metadata$ID.receveuse))

metadata$Catégories = ifelse(metadata$Catégories == "NR", "NG", "G")



y.peptide$E = y.peptide$E[,metadata$sample_ID]

y.peptide <- filterNonProteotypicPeptides(y.peptide)
y.peptide <- filterCompoundProteins(y.peptide)

dpcfit <- dpc(y.peptide)

y.protein <- dpcQuant(y.peptide, protein.id = "Protein.Group", dpc=dpcfit)

y.protein$E = y.protein$E[,metadata$sample_ID]

M.pca <- dudi.pca(y.protein$E,scale=T,center=T,scannf=F,nf=2)

s.class(M.pca$co,fac=as.factor(metadata$Catégories),col=2:6)
s.label(M.pca$co,col=2:6)
index = order(M.pca$co[,2], decreasing = F)[1:3]

y.protein = y.protein[,-index]
metadata = metadata[-index,]
```

```{r}

Group <- factor(metadata$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.protein, design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)
```

```{r}
library(EnhancedVolcano)
summary(decideTests(fit2,adjust.method="BH",p.value=0.05))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)
```

```{r}
library(mixOmics)
library(ropls)
sp = mixOmics::splsda(t(y.protein$E), metadata$Catégories, keepX = c(50,30))

plotIndiv(sp, ellipse = T, legend = T)

perfs = perf(sp, validation = "Mfold", folds = 5 , nreapeat = 10)

R2_comp1 = sp$prop_expl_var$X[1]*100

perfs$error.rate$BER
```

```{r}
library(dendextend)

gene = selectVar(sp, n=50)

gprotein = t(y.protein$E)[,gene$name]
data = scale(gprotein)
protdist = dist(data)
protclust = hclust(protdist)


GNG = metadata$Catégories

cond = as.character(unique(GNG))

couleurs = c("#E41A1C", "#377EB8")

names(couleurs) = cond

col_ech = couleurs[as.character(GNG)]

dend = as.dendrogram(protclust)

par(mar = c(10,4,4,2))
plot(dend, leaflab = "none", ylim = c(-1, max(protclust$height)))
colored_bars(colors = col_ech, dend = dend, rowLabels = "Catégories", y_shift = -0.2)
legend("topright",legend = cond, fill = couleurs, title = "Catégories", cex = 0.8, bty = "n")
```

```{r}
y.protein = y.protein[,metadata$sample_ID]
Group <- factor(metadata$Nature.embryon)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("VITRO", "VIVO")
fit <- dpcDE(y.protein, design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(VITRO - VIVO, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.05))
dfvitrovivo = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)


```

```{r}
metadatavivo = metadata[which(metadata$Nature.embryon == "VIVO"),]
y.vivo = y.protein[,metadatavivo$sample_ID]

Group <- factor(metadatavivo$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.vivo, design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.05))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)
```

```{r}
metadatavitro = metadata[which(metadata$Nature.embryon == "VITRO"),]
y.vitro = y.protein[,metadatavitro$sample_ID]

metadataA = metadatavitro[which(metadatavitro$Cat..MC == "A"),]
metadataB = metadatavitro[which(metadatavitro$Cat..MC == "B"),]
metadataC = metadatavitro[which(metadatavitro$Cat..MC == "C"),]
metadataD = metadatavitro[which(metadatavitro$Cat..MC == "D"),]

#Group A
Group <- factor(metadataA$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.vitro[,metadataA$sample_ID], design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.1))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)
```

```{r}
#Group B
Group <- factor(metadataB$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.vitro[,metadataB$sample_ID], design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.05))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)

Up = rownames(dfvitrovivo[which(dfvitrovivo$adj.P.Val < 0.05 & dfvitrovivo$logFC > 0 ),])

Down = rownames(dfvitrovivo[which(dfvitrovivo$adj.P.Val < 0.05 & dfvitrovivo$logFC < 0 ),])

updf = data.frame("Proteine" = Up, "Sens" = "UP")
dn = data.frame("Proteine" = Down, "Sens" = "DOWN")

addf = rbind(updf, dn)

write.table(addf, file = "DE_vivovitro")
```

```{r}
#Group c
Group <- factor(metadataC$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.vitro[,metadataC$sample_ID], design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.1))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)
```

```{r}
#Group D
Group <- factor(metadataD$Catégories)
design <- model.matrix(~ 0 + Group)
colnames(design) <- c("G", "NG")
fit <- dpcDE(y.vitro[,metadataD$sample_ID], design, plot=TRUE) # équivalent du lmFit limma

contrast_matrix <- makeContrasts(G - NG, levels = design)
fit2 <- contrasts.fit(fit, contrast_matrix)
fit2 <- eBayes(fit2)

summary(decideTests(fit2,adjust.method="BH",p.value=0.1))
df = topTable(fit2,number = Inf)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'P.Value', pCutoff = 0.05, FCcutoff = 1)
EnhancedVolcano(df, lab = rownames(df), x='logFC', y = 'adj.P.Val', pCutoff = 0.05, FCcutoff = 1)
```
